name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Test d'exploration GH actions
        run: |
          echo  "${{ secrets.USERNAME }}""
      - run: echo "C'est fini!"
