name: GitHub Actions Demo
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */3 * *'
jobs:
  copy-quay:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        Repo: [ desktop, os-commons, extra, kernel-stable]
    steps:
      - name: Setup luet
        run: |
          curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
          sudo luet install -y repository/mocaccino-extra-stable
      - name: Installing Skopeo
        run: |
          sudo luet install -y utils/jq container/docker container/skopeo-static
      - name: Login quay
        run: |
          echo ${{ secrets.QUAY_PASSWORD }}| docker login quay.io -u ${{ secrets.QUAY_USER }}  --password-stdin
      - name: Cloning quay repo
        env:
          REPO: ${{matrix.Repo}}
          src: "quay.io/mocaccino/$REPO"
          dst: "quay.io/capesos/$REPO"
        run: |
          echo "cloning $src => $dst"
          skopeo login quay.io
          tags=$(skopeo list-tags docker://$src | jq '.Tags')
          echo "Tag list : $tags"
          for i in $(echo "$tags" | jq -rc '.[]'); do
            echo "checking $i"
            if ! luet util image-exist $dst:$i; then
              echo "Copy docker://$src:$i docker://$dst:$i"
              skopeo --insecure-policy copy docker://$src:$i docker://$dst:$i
            fi
          done